import { TeamMember, DailyTask } from './types';

export const TRANSLATIONS = {
  en: {
    appTitle: "RS Filling Management System",
    appSubtitle: "FDPD Workflow",
    dashboard: "Dashboard",
    allTasks: "All Tasks",
    simulateRole: "Simulate Role",
    loggedInAs: "Logged in as",
    welcomeBack: "Welcome back",
    taskManagement: "Task Management",
    todayIs: "Today is",
    newFillingTask: "New Filling Task",
    pendingAssignment: "Pending Assignment",
    inProgress: "In Progress",
    completed: "Completed",
    myActiveTasks: "My Active Tasks",
    currentActiveWorkload: "Member Workload (Active vs Completed)",
    aiMorningBriefing: "AI Morning Briefing",
    clickSparkle: "Click sparkle to generate insights",
    noActiveTasks: "No active tasks assigned to you.",
    projectBatch: "Project / Batch",
    assignee: "Assignee",
    status: "Status",
    progress: "Progress (8 Steps)",
    deadline: "Deadline",
    actions: "Actions",
    viewEdit: "View / Edit",
    delete: "Delete",
    deleteTask: "Delete Task",
    confirmDelete: "Are you sure you want to delete this task?",
    confirmDeleteDetail: "This action cannot be undone. All task data and progress will be permanently deleted.",
    deleteSuccess: "Task deleted successfully",
    deleteError: "Failed to delete task",
    unassigned: "Unassigned",
    saveTask: "Save Task",
    cancel: "Cancel",
    manageTask: "Manage Task",
    newTask: "New RS Filling Task",
    projectNumberLabel: "Project Number",
    batchInfoLabel: "Batch Info",
    projectOwnerLabel: "Project Owner",
    sourceLabel: "Source",
    priorityLabel: "Priority",
    normal: "Normal",
    urgent: "Urgent",
    aiSuggest: "AI Suggest",
    thinking: "Thinking...",
    workflowTracking: "Workflow Execution (8 Steps)",
    workflowReference: "Workflow Reference",
    startDate: "Start Date",
    completionDate: "Completion Date",
    calendar: "Task Calendar",
    monthView: "Month",
    yearView: "Year",
    exportCSV: "Export CSV",
    workflowSteps: [
        "1. Process Initiation (QC/PM)",
        "2. Project Info Collection (FDPD)",
        "3. Label Prep & Shipping (QC/QA)",
        "4. Docs & Materials Prep (FDPD/QA)",
        "5. Print Tube Labels (FDPD)",
        "6. Filling & Storage (FDPD)",
        "7. Inbound/Warehousing (Operation)",
        "8. Delivery & BPR Archive (FDPD/QA)"
    ],
    roles: {
        MANAGER: "Manager",
        MEMBER: "Member"
    },
    days: "Days",
    login: "Login",
    logout: "Logout",
    username: "Username",
    password: "Password",
    loginError: "Invalid username or password"
  },
  zh: {
    appTitle: "RS Filling 管理系统",
    appSubtitle: "FDPD 工作流",
    dashboard: "仪表盘",
    allTasks: "所有任务",
    simulateRole: "模拟角色",
    loggedInAs: "当前登录",
    welcomeBack: "欢迎回来",
    taskManagement: "任务管理",
    todayIs: "今天是",
    newFillingTask: "新建灌装任务",
    pendingAssignment: "待分配",
    inProgress: "进行中",
    completed: "已完成",
    myActiveTasks: "我的进行中任务",
    currentActiveWorkload: "成员工作量 (进行中 vs 已完成)",
    aiMorningBriefing: "AI 每日简报",
    clickSparkle: "点击星号生成洞察",
    noActiveTasks: "暂无分配给您的进行中任务。",
    projectBatch: "项目 / 批次",
    assignee: "负责人",
    status: "状态",
    progress: "进度 (8步骤)",
    deadline: "截止日期",
    actions: "操作",
    viewEdit: "查看 / 编辑",
    delete: "删除",
    deleteTask: "删除任务",
    confirmDelete: "确定要删除这个任务吗？",
    confirmDeleteDetail: "此操作无法撤销。所有任务数据和进度将被永久删除。",
    deleteSuccess: "任务删除成功",
    deleteError: "删除任务失败",
    unassigned: "未分配",
    saveTask: "保存任务",
    cancel: "取消",
    manageTask: "管理任务",
    newTask: "新建 RS 灌装任务",
    projectNumberLabel: "项目编号",
    batchInfoLabel: "批次信息",
    projectOwnerLabel: "项目负责人",
    sourceLabel: "来源",
    priorityLabel: "优先级",
    normal: "普通",
    urgent: "紧急",
    aiSuggest: "AI 建议",
    thinking: "思考中...",
    workflowTracking: "执行追踪 (8步骤)",
    workflowReference: "完整工作流参考",
    startDate: "开始日期",
    completionDate: "完成日期",
    calendar: "任务日历",
    monthView: "月视图",
    yearView: "年视图",
    exportCSV: "导出 CSV",
    workflowSteps: [
        "1. RS Filling 流程开启",
        "2. FDPD收集项目信息",
        "3. 标签寄送和准备",
        "4. FDPD准备文件和物料",
        "5. FDPD打印样本管标签",
        "6. FDPD 灌装和储存",
        "7. 入库 (Operation)",
        "8. 寄送 / BPR审核和归档"
    ],
    roles: {
        MANAGER: "经理",
        MEMBER: "组员"
    },
    days: "天",
    login: "登录",
    logout: "登出",
    username: "用户名",
    password: "密码",
    loginError: "用户名或密码错误"
  }
};

export const TEAM_MEMBERS: TeamMember[] = [
  { id: 'm1', name: 'Yaohua', role: 'MANAGER', avatar: 'https://ui-avatars.com/api/?name=Yaohua&background=0f172a&color=fff' },
  { id: 'u1', name: 'Flora', role: 'MEMBER', avatar: 'https://ui-avatars.com/api/?name=Flora&background=3b82f6&color=fff' },
  { id: 'u2', name: 'Shuman', role: 'MEMBER', avatar: 'https://ui-avatars.com/api/?name=Shuman&background=8b5cf6&color=fff' },
  { id: 'u3', name: 'Yabin', role: 'MEMBER', avatar: 'https://ui-avatars.com/api/?name=Yabin&background=10b981&color=fff' },
  { id: 'u4', name: 'Wenlong', role: 'MEMBER', avatar: 'https://ui-avatars.com/api/?name=Wenlong&background=f59e0b&color=fff' },
];

// Updated to 8 Steps
export const WORKFLOW_TEMPLATE: DailyTask[] = [
  { day: 1, label: '1. Process Initiation', isCompleted: false, notes: '' },
  { day: 2, label: '2. Collect Info', isCompleted: false, notes: '' },
  { day: 3, label: '3. Label Prep', isCompleted: false, notes: '' },
  { day: 4, label: '4. Docs & Materials', isCompleted: false, notes: '' },
  { day: 5, label: '5. Print Labels', isCompleted: false, notes: '' },
  { day: 6, label: '6. Filling & Storage', isCompleted: false, notes: '' },
  { day: 7, label: '7. Inbound', isCompleted: false, notes: '' },
  { day: 8, label: '8. Delivery & Archive', isCompleted: false, notes: '' },
];

export const FULL_WORKFLOW_STEPS = [
  { step: 1, title: "1. RS Filling 流程开启", desc: "QC通知PM，PM告知FDPD (Yaohua)。至少提前2周。", phase: "Start" },
  { step: 2, title: "2. FDPD收集项目信息", desc: "Yaohua请PM填写信息收集表。RS Filling开始前1-2周。", phase: "Prep" },
  { step: 3, title: "3. 标签寄送和准备", desc: "RS Filling负责人和QA申请批号，发给QC准备标签。RS Filling开始前1-2周。", phase: "Prep" },
  { step: 4, title: "4. FDPD准备文件和物料", desc: "FDPD RS Filling负责人填写BPR给QA审核，准备物料。开始前1-3天。", phase: "Exec" },
  { step: 5, title: "5. FDPD打印样本管标签", desc: "FDPD RS Filling负责人。开始前1-3天。", phase: "Exec" },
  { step: 6, title: "6. FDPD 灌装和储存", desc: "FDPD RS Filling负责人。灌装工作正式开始 (2.5 days)。", phase: "Exec" },
  { step: 7, title: "7. 入库", desc: "Operation (样品管理员)。RS Filling 后第二天上午。", phase: "Post" },
  { step: 8, title: "8. 寄送 / BPR审核", desc: "QC/ARD/FDPD寄送样品。FDPD/QA BPR审核和归档。", phase: "End" },
];

export const MOCK_TASKS_INITIAL = [
  {
    id: 't1',
    projectNumber: 'PRJ-2024-001',
    projectOwner: 'Pharma Corp',
    source: 'External Lab',
    batchInfo: 'BATCH-A99',
    receivedDate: '2023-10-25',
    startDate: '2023-10-26',
    deadlineDate: '2023-10-31',
    assigneeId: 'u1',
    status: 'IN_PROGRESS',
    priority: 'NORMAL',
    progress: [
      { day: 1, label: '1. Process Initiation', isCompleted: true, notes: 'Done' },
      { day: 2, label: '2. Collect Info', isCompleted: true, notes: '' },
      { day: 3, label: '3. Label Prep', isCompleted: true, notes: '' },
      { day: 4, label: '4. Docs & Materials', isCompleted: true, notes: '' },
      { day: 5, label: '5. Print Labels', isCompleted: false, notes: '' },
      { day: 6, label: '6. Filling & Storage', isCompleted: false, notes: '' },
      { day: 7, label: '7. Inbound', isCompleted: false, notes: '' },
      { day: 8, label: '8. Delivery & Archive', isCompleted: false, notes: '' },
    ]
  },
  {
    id: 't2',
    projectNumber: 'PRJ-2024-005',
    projectOwner: 'BioTech Inc',
    source: 'Internal',
    batchInfo: 'BATCH-X12',
    receivedDate: '2023-10-26',
    startDate: '2023-10-27',
    deadlineDate: '2023-11-01',
    assigneeId: null,
    status: 'PENDING',
    priority: 'URGENT',
    progress: WORKFLOW_TEMPLATE
  }
];